import '../styles/globals.css'

import type { Metadata } from 'next'

import RootProvider from '@/components/provider/RootProvider'
import RootLayout from '@/components/layout/RootLayout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function Layout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <RootProvider>
          <RootLayout>{children}</RootLayout>
        </RootProvider>
      </body>
    </html>
  )
}
